apiVersion: v1
kind: Secret
metadata:
  name: kurbernetes-secret
  namespace: default
stringData:
  rclone.conf: |
    [s3-remote]
    type = s3
    access_key_id = access_key_id
    secret_access_key = secret_access_key
    region = eu-central-1
    location_constraint = eu-central-1
    provider = AWS
